# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'vector-batch'
    scrape_interval: 1s
    static_configs:
      - targets: ['vector-batch:9494']

  - job_name: 'vector-stream'
    scrape_interval: 1s
    static_configs:
      - targets: ['vector-stream:9494']

  - job_name: 'lading'
    scrape_interval: 1s
    static_configs:
      - targets: ['lading:8383']
